# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Runner info
      run: |
        echo "RUNNER_OS: $env:RUNNER_OS"
        echo "RUNNER_ARCH: $env:RUNNER_ARCH"
        echo "RUNNER_DEBUG: $env:RUNNER_DEBUG"

    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Install packages and dependencies
      run: |
        bootstrap-vcpkg
        vcpkg integrate install

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Executable
        path: ${{ env:RUNNER_ARCH }}/${{ env.BUILD_CONFIGURATION }}/*.exe
        # auto-delete the artifacts
        retention-days: 5
